import { Listing, UserProfile, WantedPost, NotificationItem } from '../types';

export const DEMO_USERS: UserProfile[] = [
  {
    uid: 'demo_aarav_sharma',
    displayName: 'Aarav Sharma',
    email: 'aarav.sharma@campus.edu.in',
    photoURL: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    college: 'Main Tech Campus',
    verifiedCampus: true,
    rating: 4.9,
    totalSales: 14,
    totalListings: 4,
    createdAt: '2024-08-15T09:00:00.000Z',
    lastLoginAt: new Date().toISOString(),
    hostelOrBlock: 'Hostel 3, Block B (Room 114)',
    phoneOrContact: '+91 98765 43210',
    bio: '3rd Year Electrical Engineering. Clearing out books, lab accessories & study tech.',
    memberSince: 'Aug 2024',
    // Compatibility helpers
    id: 'demo_aarav_sharma',
    name: 'Aarav Sharma',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    salesCount: 14,
  },
  {
    uid: 'demo_priya_patel',
    displayName: 'Priya Patel',
    email: 'priya.patel@campus.edu.in',
    photoURL: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
    college: 'Main Tech Campus',
    verifiedCampus: true,
    rating: 4.8,
    totalSales: 8,
    totalListings: 3,
    createdAt: '2025-01-10T11:00:00.000Z',
    lastLoginAt: new Date().toISOString(),
    hostelOrBlock: 'Kaveri Girls Hostel, Room 204',
    phoneOrContact: '+91 98234 56789',
    bio: '2nd Year Computer Science student. Frequent buyer and seller of engineering textbooks and coding gear.',
    memberSince: 'Jan 2025',
    // Compatibility helpers
    id: 'demo_priya_patel',
    name: 'Priya Patel',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
    salesCount: 8,
  },
  {
    uid: 'demo_rohan_gupta',
    displayName: 'Rohan Gupta',
    email: 'rohan.gupta@campus.edu.in',
    photoURL: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    college: 'Main Tech Campus',
    verifiedCampus: true,
    rating: 4.9,
    totalSales: 19,
    totalListings: 5,
    createdAt: '2023-07-20T14:30:00.000Z',
    lastLoginAt: new Date().toISOString(),
    hostelOrBlock: 'Hostel 7, Room 318',
    phoneOrContact: '+91 97123 45678',
    bio: '4th Year Mechanical Engineering. Campus cyclist and mechanical keyboard enthusiast.',
    memberSince: 'Jul 2023',
    // Compatibility helpers
    id: 'demo_rohan_gupta',
    name: 'Rohan Gupta',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    salesCount: 19,
  }
];

export const INITIAL_SEED_LISTINGS: Listing[] = [
  {
    id: 'seed_listing_1',
    sellerId: 'demo_aarav_sharma',
    sellerName: 'Aarav Sharma',
    sellerPhotoURL: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    sellerRating: 4.9,
    title: 'Higher Engineering Mathematics - B.S. Grewal (44th Ed)',
    description: 'Clean copy with no torn pages or ink marks. Formula quick sheets preserved at the back. Essential for 1st & 2nd year B.Tech mathematics courses (Calculus, Differential Equations, Transform Calculus).',
    category: 'Textbooks',
    condition: 'Like New',
    price: 450,
    originalPrice: 850,
    negotiable: true,
    location: 'Hostel 3, Block B (Room 114)',
    imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80',
    status: 'available',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    views: 94,
    tags: ['books', 'engineering maths', 'textbook', 'grewal', 'maths'],
    isNegotiable: true,
    sellerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    sellerSalesCount: 14,
  },
  {
    id: 'seed_listing_2',
    sellerId: 'demo_priya_patel',
    sellerName: 'Priya Patel',
    sellerPhotoURL: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
    sellerRating: 4.8,
    title: 'Casio FX-991ES Plus Scientific Calculator',
    description: 'Original Casio scientific calculator with 417 functions and matrix/vector modes. Approved for mid-sems and end-sems. Fresh battery replaced last month with protective slide-on hard case included.',
    category: 'Electronics',
    condition: 'Gently Used',
    price: 450,
    originalPrice: 1250,
    negotiable: true,
    location: 'CV Raman Hall / Campus Handover',
    imageUrl: 'https://images.unsplash.com/photo-1594980596870-8aa52a78d8cd?auto=format&fit=crop&w=800&q=80',
    status: 'available',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    views: 145,
    tags: ['calculator', 'casio', 'electronics', 'scientific', 'exam', 'engineering calculator'],
    isNegotiable: true,
    sellerAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
    sellerSalesCount: 8,
  },
  {
    id: 'seed_listing_3',
    sellerId: 'demo_rohan_gupta',
    sellerName: 'Rohan Gupta',
    sellerPhotoURL: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    sellerRating: 4.9,
    title: 'College Bicycle - Hero Sprint with Basket & Bell',
    description: 'Perfect daily commuter campus cycle for hostel to lecture hall transit. Recently tuned up at campus cycle repair shop with new brake pads and smooth chain lube. Includes heavy-duty number combination cable lock.',
    category: 'Cycles & Mobility',
    condition: 'Gently Used',
    price: 2500,
    originalPrice: 5800,
    negotiable: true,
    location: 'Hostel 7 Bicycle Stand',
    imageUrl: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=800&q=80',
    status: 'available',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    views: 236,
    tags: ['cycle', 'bicycle', 'transport', 'campus', 'hostel'],
    isNegotiable: true,
    sellerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    sellerSalesCount: 19,
  },
  {
    id: 'seed_listing_4',
    sellerId: 'demo_aarav_sharma',
    sellerName: 'Aarav Sharma',
    sellerPhotoURL: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    sellerRating: 4.9,
    title: 'Ergonomic Aluminium Laptop Stand (Adjustable 6-Angles)',
    description: 'Foldable aircraft-grade aluminium laptop riser with silicone anti-slip pads and carry pouch. Fits 11" to 16" laptops (MacBook, ThinkPad, Dell XPS). Prevents neck strain during long coding nights and project submissions.',
    category: 'Accessories',
    condition: 'Like New',
    price: 380,
    originalPrice: 899,
    negotiable: true,
    location: 'Aryabhatta Hostel, Room 302',
    imageUrl: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=800&q=80',
    status: 'available',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    views: 71,
    tags: ['laptop', 'stand', 'accessories', 'coding', 'hostel'],
    isNegotiable: true,
    sellerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    sellerSalesCount: 14,
  },
  {
    id: 'seed_listing_5',
    sellerId: 'demo_aarav_sharma',
    sellerName: 'Aarav Sharma',
    sellerPhotoURL: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    sellerRating: 4.9,
    title: 'Official College Chemistry & Physics Lab Coat (Size L, Unisex)',
    description: '100% thick white cotton lab coat with college embroidered crest patch on pocket. Required for 1st year Chemistry, Environmental science, and Biotech practicals. Freshly laundered and pressed.',
    category: 'Clothing & Merch',
    condition: 'Gently Used',
    price: 220,
    originalPrice: 600,
    negotiable: false,
    location: 'Science Complex, Room 102',
    imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80',
    status: 'available',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 16).toISOString(),
    views: 98,
    tags: ['lab coat', 'practical', 'chemistry', 'college', 'clothing'],
    isNegotiable: false,
    sellerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    sellerSalesCount: 14,
  },
  {
    id: 'seed_listing_6',
    sellerId: 'demo_priya_patel',
    sellerName: 'Priya Patel',
    sellerPhotoURL: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
    sellerRating: 4.8,
    title: 'Multi-Purpose Foldable Hostel Study Bed Table',
    description: 'Heavy duty wooden top foldable bed table with tablet slot and cup holder. Ideal for studying from hostel bed or floor during winter exam weeks. Sturdy steel legs that fold flat for quick storage behind wardrobes.',
    category: 'Hostel Essentials',
    condition: 'Gently Used',
    price: 320,
    originalPrice: 750,
    negotiable: false,
    location: 'Kaveri Girls Hostel, Ground Floor',
    imageUrl: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=800&q=80',
    status: 'available',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
    views: 114,
    tags: ['table', 'hostel', 'study table', 'furniture', 'bed'],
    isNegotiable: false,
    sellerAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
    sellerSalesCount: 8,
  },
  {
    id: 'seed_listing_7',
    sellerId: 'demo_rohan_gupta',
    sellerName: 'Rohan Gupta',
    sellerPhotoURL: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    sellerRating: 4.9,
    title: 'Redragon Mechanical Keyboard (Blue Switches, RGB)',
    description: 'Compact 87-key tenkeyless tactile mechanical keyboard. Clicky Outemu Blue switches, customizable rainbow LED backlighting, braided USB cable. Used for competitive programming contests and typing assignments.',
    category: 'Electronics',
    condition: 'Gently Used',
    price: 1350,
    originalPrice: 2899,
    negotiable: true,
    location: 'Hostel 9, Room 418',
    imageUrl: 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&w=800&q=80',
    status: 'available',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 22).toISOString(),
    views: 319,
    tags: ['keyboard', 'mechanical keyboard', 'electronics', 'gaming', 'coding'],
    isNegotiable: true,
    sellerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    sellerSalesCount: 19,
  },
  {
    id: 'seed_listing_8',
    sellerId: 'demo_priya_patel',
    sellerName: 'Priya Patel',
    sellerPhotoURL: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
    sellerRating: 4.8,
    title: 'Sony Wireless Bluetooth Headphones with Mic (35h Battery)',
    description: 'Active noise dampening over-ear headphones with 35 hours battery life and quick charge. Built-in mic for viva calls and Zoom presentations. Beige color, pristine ear cushions without any peel or scuff marks.',
    category: 'Electronics',
    condition: 'Like New',
    price: 1850,
    originalPrice: 4490,
    negotiable: true,
    location: 'Central Library Lawn / Food Court',
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    status: 'available',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
    views: 428,
    tags: ['headphones', 'sony', 'audio', 'bluetooth', 'electronics'],
    isNegotiable: true,
    sellerAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
    sellerSalesCount: 8,
  },
  {
    id: 'seed_listing_9',
    sellerId: 'demo_rohan_gupta',
    sellerName: 'Rohan Gupta',
    sellerPhotoURL: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    sellerRating: 4.9,
    title: 'Wildcraft 35L Water-Resistant College Backpack',
    description: 'Three large zippered compartments with padded 15.6" laptop sleeve and twin water bottle side mesh pockets. Hidden bottom pocket contains fluorescent water-proof rain poncho cover for rainy monsoon semesters.',
    category: 'Accessories',
    condition: 'Gently Used',
    price: 790,
    originalPrice: 2199,
    negotiable: true,
    location: 'Bhabha Hostel, Room 109',
    imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
    status: 'available',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
    views: 168,
    tags: ['backpack', 'wildcraft', 'bag', 'laptop bag', 'hostel'],
    isNegotiable: true,
    sellerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    sellerSalesCount: 19,
  },
  {
    id: 'seed_listing_10',
    sellerId: 'demo_rohan_gupta',
    sellerName: 'Rohan Gupta',
    sellerPhotoURL: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    sellerRating: 4.9,
    title: 'Godrej 45L Compact Hostel Mini Refrigerator / Chiller',
    description: 'Energy-efficient 5-star mini fridge. Fits cold drinks, milk packets, medicine, and food containers. Runs ultra quiet, does not trip hostel 5A switchboard limit. Perfect for hot summer semesters. Self pickup from ground floor.',
    category: 'Hostel Essentials',
    condition: 'Gently Used',
    price: 4900,
    originalPrice: 10500,
    negotiable: true,
    location: 'Hostel 1, Ground Floor Room 008',
    imageUrl: 'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=800&q=80',
    status: 'available',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 42).toISOString(),
    views: 546,
    tags: ['mini fridge', 'refrigerator', 'hostel', 'appliance', 'summer'],
    isNegotiable: true,
    sellerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    sellerSalesCount: 19,
  },
  {
    id: 'seed_listing_11',
    sellerId: 'demo_aarav_sharma',
    sellerName: 'Aarav Sharma',
    sellerPhotoURL: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    sellerRating: 4.9,
    title: 'Computer Science Core Textbook Bundle & Used Academic Notes',
    description: 'Includes Cormen Algorithms (CLRS), Tanenbaum Computer Networks, Silberschatz Operating Systems, and handwritten toppers GATE exam notes with neat diagrams.',
    category: 'Textbooks',
    condition: 'Gently Used',
    price: 1100,
    originalPrice: 3200,
    negotiable: true,
    location: 'Tagore Hostel, Room 221',
    imageUrl: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=800&q=80',
    status: 'available',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    views: 284,
    tags: ['books', 'notes', 'used academic notes', 'computer science', 'gate'],
    isNegotiable: true,
    sellerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    sellerSalesCount: 14,
  },
  {
    id: 'seed_listing_12',
    sellerId: 'demo_priya_patel',
    sellerName: 'Priya Patel',
    sellerPhotoURL: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
    sellerRating: 4.8,
    title: 'Rechargeable LED Desk Study Lamp with Phone Mount',
    description: '3 color temperatures (warm, cool white, natural) and touch dimming. Built-in 2000mAh battery that lasts 8 hours during campus power outages. Flexible 360-degree gooseneck with USB-C charging cord included.',
    category: 'Hostel Essentials',
    condition: 'Like New',
    price: 290,
    originalPrice: 650,
    negotiable: false,
    location: 'Sarojini Naidu Hostel, 1st Floor',
    imageUrl: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=800&q=80',
    status: 'available',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 52).toISOString(),
    views: 139,
    tags: ['desk lamp', 'lamp', 'study', 'hostel', 'light'],
    isNegotiable: false,
    sellerAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
    sellerSalesCount: 8,
  },
  {
    id: 'seed_listing_13',
    sellerId: 'demo_aarav_sharma',
    sellerName: 'Aarav Sharma',
    sellerPhotoURL: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    sellerRating: 4.9,
    title: 'Havells 3-Socket Surge Protector Extension Board (3-Metre Cable)',
    description: 'Essential for hostel rooms with limited wall sockets. 3 universal sockets plus master reset switch and surge protection circuit to safeguard laptop and phone chargers against campus voltage spikes.',
    category: 'Hostel Essentials',
    condition: 'Gently Used',
    price: 260,
    originalPrice: 525,
    negotiable: false,
    location: 'Hostel 2, Room 104',
    imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80',
    status: 'available',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 60).toISOString(),
    views: 82,
    tags: ['extension board', 'electronics', 'hostel', 'charger', 'socket'],
    isNegotiable: false,
    sellerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    sellerSalesCount: 14,
  },
  {
    id: 'seed_listing_14',
    sellerId: 'demo_rohan_gupta',
    sellerName: 'Rohan Gupta',
    sellerPhotoURL: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    sellerRating: 4.9,
    title: 'Engineering Drawing Tools Kit (Mini Drafter, Compass & Sheet Container)',
    description: 'Complete mechanical & civil engineering drawing set: Omega mini drafter, steel compass set, protractor, set squares, and water-proof cylindrical drawing sheet holder with shoulder strap.',
    category: 'Textbooks',
    condition: 'Like New',
    price: 490,
    originalPrice: 1250,
    negotiable: true,
    location: 'Hostel 7, Room 318',
    imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80',
    status: 'available',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 65).toISOString(),
    views: 110,
    tags: ['engineering drawing tools', 'drafter', 'drawing', 'first year', 'tools'],
    isNegotiable: true,
    sellerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    sellerSalesCount: 19,
  }
];

export const INITIAL_WANTED_POSTS: WantedPost[] = [
  {
    id: 'seed_wanted_1',
    title: 'Advanced Engineering Mathematics (Erwin Kreyszig 10th Ed)',
    description: 'Looking for a clean copy for mid-sems. No missing pages please.',
    category: 'Textbooks',
    budget: 400,
    condition: 'Gently Used or Like New',
    neededBy: 'This Friday',
    preferredLocation: 'Central Library / Gate 1',
    userId: 'demo_priya_patel',
    userName: 'Priya Patel',
    userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
    status: 'active',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
  {
    id: 'seed_wanted_2',
    title: 'Casio Scientific Calculator FX-991EX Classwiz',
    description: 'Need urgently for Semester 3 thermodynamics & signals exams. Must have working matrix functions.',
    category: 'Electronics',
    budget: 550,
    condition: 'Working condition with cover',
    neededBy: 'Tomorrow (Exam)',
    preferredLocation: 'CV Raman Hall or Library',
    userId: 'demo_aarav_sharma',
    userName: 'Aarav Sharma',
    userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    status: 'active',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
  },
  {
    id: 'seed_wanted_3',
    title: 'Single Speed Campus Bicycle with Lock',
    description: 'Looking for a reliable cycle for hostel to lecture hall commute. Hero, Hercules or Firefox.',
    category: 'Cycles & Mobility',
    budget: 2200,
    condition: 'Good brakes & tyres',
    neededBy: 'This Weekend',
    preferredLocation: 'Hostel 7 Bicycle Stand',
    userId: 'demo_priya_patel',
    userName: 'Priya Patel',
    userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
    status: 'active',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
  {
    id: 'seed_wanted_4',
    title: 'Electric Kettle for Hostel (1.2L or 1.5L)',
    description: 'Need for late-night coffee & noodles in hostel room. Auto-cutoff preferred.',
    category: 'Hostel Essentials',
    budget: 450,
    condition: 'Clean interior, working heater',
    neededBy: 'Within 3 days',
    preferredLocation: 'Hostel 3 Mess',
    userId: 'demo_rohan_gupta',
    userName: 'Rohan Gupta',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    status: 'active',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 30).toISOString(),
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'seed_notif_1',
    userId: 'demo_aarav_sharma',
    type: 'new_offer',
    title: 'New Offer Received',
    message: 'Priya offered ₹400 for your B.S. Grewal Mathematics Textbook.',
    listingId: 'seed_listing_1',
    read: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
  },
  {
    id: 'seed_notif_2',
    userId: 'demo_aarav_sharma',
    type: 'price_drop',
    title: 'Price Drop Alert',
    message: 'College Bicycle - Hero Sprint dropped to ₹2,500 (Matches your target price!)',
    listingId: 'seed_listing_3',
    read: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
  },
  {
    id: 'seed_notif_3',
    userId: 'demo_aarav_sharma',
    type: 'wanted_post_match',
    title: 'Wanted Post Match!',
    message: 'A student posted a request for "Engineering Mathematics" matching your active listing.',
    wantedPostId: 'seed_wanted_1',
    read: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
  },
];

